# Generated by Django 4.0.4 on 2022-05-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
