# Generated by Django 4.0.4 on 2022-05-10 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
